# Generated by Django 2.0.1 on 2018-06-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='promo_type',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
    ]
