# Generated by Django 2.0.1 on 2018-06-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_auto_20180625_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='promo_type',
            field=models.CharField(default='', max_length=500),
        ),
    ]
