# Generated by Django 2.0.1 on 2018-06-25 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_auto_20180625_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promo_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.PromoType'),
        ),
    ]
