# Generated by Django 2.0.1 on 2018-01-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='display_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rrp_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='search_price',
        ),
    ]
