# Generated by Django 2.0.1 on 2018-02-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180205_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
