# Generated by Django 2.0.1 on 2018-05-17 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180517_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colour',
            old_name='colourOptions',
            new_name='colour',
        ),
    ]
