# Generated by Django 2.0.1 on 2018-05-17 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180517_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colourOptions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Colour'),
        ),
    ]
