# Generated by Django 2.0.1 on 2018-02-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180208_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='regex',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
