# Generated by Django 2.0.1 on 2018-06-09 16:39

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180517_2111'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('sale_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
