# Generated by Django 2.0.1 on 2018-02-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180205_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rrp_price',
            field=models.CharField(default='', max_length=500),
        ),
    ]
