# Generated by Django 2.0.1 on 2018-06-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180609_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rrp_price',
            field=models.DecimalField(decimal_places=2, default='', max_digits=6, null=True),
        ),
    ]
