# Generated by Django 2.0.1 on 2018-07-09 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180625_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colourOptions',
        ),
        migrations.AlterField(
            model_name='colour',
            name='colour',
            field=models.CharField(choices=[(1, 'Red'), (2, 'Blue')], default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='colour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Colour'),
        ),
    ]
