# Generated by Django 2.0.1 on 2018-07-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180709_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colour',
            name='colour',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue')], default='', max_length=500),
        ),
    ]
